DockerDemoApp:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
    io.rancher.scheduler.affinity:host_label: env=tst,component=frontend
  tty: true
  image: 619528312477.dkr.ecr.us-east-1.amazonaws.com/docker-demo-app:latest
  stdin_open: true
  ports:
  - "80:80"